### PR TITLE
Pr fix pb latency

### PR DESCRIPTION
**Pull request by RomanBapst**
This greatly reduces the amount of log file we lose after arming a drone when streaming the log to a PocketBeagle.
I quickly tested this on Friday and with a spool up time of 2 seconds we pretty much have the log from beginning.
@catch-twenty-two @bkueng FYI

### CODE REVIEW

**Comment by catch-twenty-two** [comment]
Thanks for testing this Roman, @bkueng let me know if you have any concerns,  I'm going to clean it up a bit and add a timer that turns up the nice level automatically after 3 seconds, just in case something gets stuck.

**Comment by catch-twenty-two** [comment]
I went ahead and separated out the logic for the fix

**Comment by bkueng** [comment]
> This greatly reduces the amount of log file we lose after arming a drone when streaming the log to a PocketBeagle.

During bootup or in general?

I find the approach a bit questionable. Why not let mavlink-router run at high prio during startup, or just altogether? It's a very important component, and it's generally efficient, so we can keep it at higher prio.

**Comment by catch-twenty-two** [comment]
@bkueng The only part of the log writing process that creates a problem is the turn around time for the acknowledgement algorithm when the header is transferred (which takes aprox 2-3 seconds with the fix and 15-20 secs without).  After that it is fine and the bottle neck or packet dropping problem isn't helped by it. (I had tested this just to make sure) I didn't think it was necessary to possibly starve other processes if it wasn't needed. We can set it permanently in the boot script, but I would be worried about that leading to problems elsewhere with other processes if it was set 100% of the time.

**Comment by bkueng** [comment]
Increased latency is also a problem for vision.
I'd just increase the prio permanently and then see if we have problems (I don't expect any).

> which takes aprox 2-3 seconds with the fix and 15-20 secs without

That's a huge difference. Is that during startup? What's the CPU load?

**Comment by catch-twenty-two** [comment]
It isn't cpu load that's the problem, it's the user space scheduler, it's just not prioritizing the application after each packet is received and it requests the process to sleep in between polling the file descriptors. With the nice value mavlink router is using around 25% of total cpu. Without changing the nice value, the average time for turn around is around 80 ms for each packet, there are 170 packets initially sent.  Changing the nice value drops this to ~15 ms per packet.  We can't get much better than that because the driver is set to execute by the kernel scheduler which has default tick "wait" rate is set at 10 ms. I'm not opposed to trying it and seeing what happens, it's an easy change let's try setting the nice value to -20 at boot and see what happens it would be good to test this a lot though.  I'm wondering if we might do better with a kernel compiled for real time so we have a more predictive schedule time for each process, and I wouldn't worry about it as much. I think we are going to have to eventually compile and deploy our own version of the Balena kernel/OS image, it seems like there are a bunch of issues that we are going to run up against with these problems.

**Comment by catch-twenty-two** [comment]
@bkueng closing this pr in favor of this one: https://github.com/Auterion/auterion_distro_resin/pull/179

**Pull request closed without merging**
