### PR TITLE
Clean gtest

### PR DESCRIPTION
**Pull request by caleridas**
Rework test/gtest infrastructure conforming to usual automake mechanisms. Provide sample test in mainloop and fix variable concurrently accessed by signal handler.

### CODE REVIEW

**Comment by bkueng** [comment]
Can we pull in master from upstream, since that got merged already?

**Comment by caleridas** [comment]
> Can we pull in master from upstream, since that got merged already?

Sure, thought we would internally have a look at it, still. Fine to just go ahead and pull upstream and drop this PR insteah.

**Comment by bkueng** [comment]
> Sure, thought we would internally have a look at it, still.

We use the `auterion-router-latest` in the distro and merge `master` into that (with a PR).

**Comment by caleridas** [comment]
> > Sure, thought we would internally have a look at it, still.
> 
> We use the `auterion-router-latest` in the distro and merge `master` into that (with a PR).

Actually I want to consistently use master for everything in the distro.

**Comment by bkueng** [comment]
I don't mind that, as long as we have a clear workflow.

**Comment by caleridas** [comment]
what about this change, can we either pull this from upstream or merge this here?

**Comment by bkueng** [comment]
Sorry I forgot, let's bring in upstream: https://github.com/Auterion/mavlink-router/pull/21

**Pull request closed without merging**
