### PR TITLE
adding logging heartbeat option to mavlink-router

### PR DESCRIPTION
**Pull request by catch-twenty-two**
This pr adds the ability for the mavlink router to broadcast a heartbeat with it's status. It can be used to make sure the logger is up and running before arming a vehicle.

### CODE REVIEW

**Comment by catch-twenty-two** [comment]
@bkueng is concerned with user confusion if the drone doesn't arm because mavlink router logging isn't ready.  I explained that the router will run exactly the same as before if you don't add the parameter to send out a heartbeat (-b <sisid>).  On the FMU side I was going to add a configurable parameter to deny arming with no log heartbeat, with the default being off. @bkueng @DanielePettenuzzo @RomanBapst let me know if this sounds like a good plan. If not, any ideas for a different approach?

**Comment by catch-twenty-two** [comment]
As far as buffering the log and downloading it after the drone is flying and in the air, the problem with this is you loose logging on the tail end instead of on the front end if for whatever reason the drone is shut off before all the logs are uploaded. I think the only real fix is to wait until the drone is ready then fly,  which involves getting boot times down.  I have been looking into this and was able to get times down to around 42 seconds from power up to start a script in the container.

**Comment by bkueng** [comment]
The intent was not clear to me initially. The approach is ok.
I'm not sure we even need the `-b` parameter. And can you avoid having to specify the sysid? It should learn that from the autopilot. I think you already have it in `_target_system_id`.

**Comment by catch-twenty-two** [comment]
> The intent was not clear to me initially. The approach is ok.
> I'm not sure we even need the `-b` parameter. And can you avoid having to specify the sysid? It should learn that from the autopilot. I think you already have it in `_target_system_id`.

This seemed like a good idea but after I looked at the code more closesly there could be a race condition if the logger has started but it hasn't gotten a heartbeat from the autopilot.  This or the logger would have start, then to wait until it got the first heartbeat from the autopilot then start sending it's heartbeat...

**Comment by bkueng** [comment]
> This seemed like a good idea but after I looked at the code more closesly there could be a race condition if the logger has started but it hasn't gotten a heartbeat from the autopilot.

It's not a race condition, it's just a dependency, which we already have (we cannot log w/o the autopilot), and needs to be handled accordingly.
I don't think it's an issue.

**Comment by catch-twenty-two** [comment]
Ah, Ok! I didn't realize that the armed status was actually in the heartbeat (I thought it was a separate message)  Okay, yes this makes complete sense. Ill make the changes.

**Comment by catch-twenty-two** [comment]
> > This seemed like a good idea but after I looked at the code more closesly there could be a race condition if the logger has started but it hasn't gotten a heartbeat from the autopilot.
> 
> It's not a race condition, it's just a dependency, which we already have (we cannot log w/o the autopilot), and needs to be handled accordingly.
> I don't think it's an issue.

So, when the mavlink router starts up it instantiates a logger even before it starts logging, at this point the logger is broadcasting that it is "ready to log"  but if it hasn't gotten an id because it hasn't gotten a sysid from the autopilot i'm not sure what sysid id it should broadcast at this point.  Should it just hold off broadcasting a heartbeat until it gets the id?

**Comment by catch-twenty-two** [comment]
I guess it could broadcast the default id until it gets a heartbeat from the autopilot then switch to that one. That would probably be confusing to users though...Any other ideas?

**Comment by bkueng** [comment]
I'd say wait until the autopilot is up, since that is generally up and running before the companion is. In isolated testing environments you would not get the heartbeat, but I think that's ok.

**Comment by catch-twenty-two** [comment]
@bkueng the changes have been made, everything seems to work good here is fmu output under normal operation (notice the transition of 155 an on board logger from status 3 to 4):

Got onboard heartbeat 155, 3
Got onboard heartbeat 155, 3
Got onboard heartbeat 155, 3
INFO  [logger] Start file log (type: full)
INFO  [logger] Opened full log file: /fs/microsd/log/2019-05-15/23_08_17.ulg
Got onboard heartbeat 155, 4
INFO  [logger] Start mavlink log
Got onboard heartbeat 155, 4
Got onboard heartbeat 155, 4
Got onboard heartbeat 155, 4
Got onboard heartbeat 155, 4
Got onboard heartbeat 155, 4
Got onboard heartbeat 155, 4
INFO  [logger] Stop mavlink log
Got onboard heartbeat 155, 3
INFO  [logger] closed logfile, bytes written: 239363
Got onboard heartbeat 155, 3
Got onboard heartbeat 155, 3

Here is what happens when the logger fails to opena new log file:

Got onboard heartbeat 155, 3
Got onboard heartbeat 155, 3
INFO  [logger] Start file log (type: full)
INFO  [logger] Opened full log file: /fs/microsd/log/2019-05-15/23_05_37.ulg
Got onboard heartbeat 155, 3
Got onboard heartbeat 155, 3
Got onboard heartbeat 155, 3

**Comment by catch-twenty-two** [comment]
@bkueng changed the base, it should be ready to merge now

**Pull request merged**
